steps:
  - imports:
      align: global
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - simple_align:
      records: true
  - trailing_whitespace: {}

columns: 80

language_extensions:
  - MultiParamTypeClasses
  - TypeOperators
  - DataKinds
